version: "3.4"
services:
  app:
    build:
      context: .
      target: ledger_redux_base
      dockerfile: ./.docker/development/Dockerfile
      args:
        BUNDLER_VERSION_OVERRIDE: '2.1.4'
    image: ledger_redux:dev-0.1.0
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/ledger_redux:cached
      # - rails_cache:/ledger_redux/tmp/cache
      - bundle:/bundle
      - node_modules:/ledger_redux/node_modules
      # - packs:/ledger_redux/public/packs
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - DB_DATABASE=ledger_redux_development
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres_local
      - DB_HOST=db
      - DB_PORT=5432
      - AMQP_HOST=${AMQP_HOST:-amqp}
      - AMQP_PORT=${AMQP_PORT:-5672}
      - AMQP_USERNAME=${AMQP_USERNAME:-guest}
      - AMQP_PASSWORD=${AMQP_PASSWORD:-guest}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-AKIA123456789}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-AbcD987654321}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_S3_ROOT_NAMESPACE=${AWS_S3_ROOT_NAMESPACE:-root_bucket}
      - AWS_BUCKET_ROOT_NAMESPACE=${AWS_BUCKET_ROOT_NAMESPACE:-root_bucket}
      - AWS_CONNECT_INSTANCE_ID=${AWS_CONNECT_INSTANCE_ID:-123456789}
      - AWS_CONNECT_INSTANCE_URL=${AWS_CONNECT_INSTANCE_URL:-http://localhost}
      - ACTION_MAILER_HOST=${ACTION_MAILER_HOST:-localhost}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_HOST=${SMTP_HOST:-localhost}
      - SMTP_DOMAIN=${SMTP_DOMAIN:-ideacrew.com}
      - SMTP_USERNAME=${SMTP_USERNAME:-username}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-password}
      - WF_API_KEY=${WF_API_KEY:-1234567890}
      - WF_BILLER_KEY=${WF_API_KEY:-1234567890}
      - WF_API_SECRET=${WF_API_KEY:-1234567890}
      - WF_PRIVATE_KEY=${WF_API_KEY:-1234567890}
      - QB_CLIENT_ID=${QB_CLIENT_ID:-1234567890}
      - QB_CLIENT_SECRET=${QB_CLIENT_SECRET:-1234567890}
      - QB_REALM_ID=${QB_REALM_ID:-1234567890}
    command: bash -c "rm -f tmp/pids/server.pid && mkdir -p tmp/pids && yarn install --check-files && bundle exec rails assets:precompile && bundle exec puma -C config/puma.rb"
  db:
    image: postgis/postgis:12-3.0
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ledger_redux_development
      - POSTGRES_PASSWORD=postgres_local
  enroll_web:
    image: ideacrew/enroll:dev-0.1.0
    links:
      - enroll_db
    ports:
      - "3001:3000"
    volumes:
      - enroll_bundle:/bundle
      - enroll_node_modules:/enroll/node_modules
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - DB_DATABASE=enroll_development
      - DB_USERNAME=enroll
      - DB_PASSWORD=enroll_local
      - DB_HOST=enroll_db
      - DB_PORT=27017
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-AKIA123456789}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-AbcD987654321}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_S3_ROOT_NAMESPACE=${AWS_S3_ROOT_NAMESPACE:-root_bucket}
      - AWS_BUCKET_ROOT_NAMESPACE=${AWS_BUCKET_ROOT_NAMESPACE:-root_bucket}
      - ACTION_MAILER_HOST=${ACTION_MAILER_HOST:-localhost}
      - HBX_ID=${HBX_ID:-dc0}
      - ENV_NAME=${ENV_NAME:-dev}
      - ACAPI_BROKER_HOST=${ACAPI_BROKER_HOST:-amqp}
      - ACAPI_BROKER_PORT=${ACAPI_BROKER_PORT:-5672}
      - RABBITMQ_URL=${RABBITMQ_URL:-amqp://guest:guest@amqp:5672}
    command: bash -c "rm -f tmp/pids/server.pid && mkdir -p tmp/pids && yarn install --check-files && bundle install && bundle exec puma -C config/puma.rb"
  enroll_remote_event_listener:
    image: ideacrew/enroll:dev-0.1.0
    ports:
      - 3000
    links:
      - enroll_db
    volumes:
      - enroll_bundle:/bundle
      - enroll_node_modules:/enroll/node_modules
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - DB_DATABASE=enroll_development
      - DB_USERNAME=enroll
      - DB_PASSWORD=enroll_local
      - DB_HOST=enroll_db
      - DB_PORT=27017
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-AKIA123456789}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-AbcD987654321}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_S3_ROOT_NAMESPACE=${AWS_S3_ROOT_NAMESPACE:-root_bucket}
      - AWS_BUCKET_ROOT_NAMESPACE=${AWS_BUCKET_ROOT_NAMESPACE:-root_bucket}
      - ACTION_MAILER_HOST=${ACTION_MAILER_HOST:-localhost}
      - HBX_ID=${HBX_ID:-dc0}
      - ENV_NAME=${ENV_NAME:-dev}
      - ACAPI_BROKER_HOST=${ACAPI_BROKER_HOST:-amqp}
      - ACAPI_BROKER_PORT=${ACAPI_BROKER_PORT:-5672}
      - RABBITMQ_URL=${RABBITMQ_URL:-amqp://guest:guest@amqp:5672}
    command: bash -c "rm -f tmp/pids/server.pid && mkdir -p tmp/pids && sleep 20 && bundle exec rails runner script/remote_event_listener.rb"
  enroll_db:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/db_config
    ports:
      - 27017:27017
  amqp:
    image: rabbitmq:3.8-management
    build:
      context: .
      dockerfile: ./.docker/development/Dockerfile.rabbitmq
      args:
        HBX_ID: 'dc0'
        ENV_NAME: 'dev'
    image: ledger_redux_amqp:dev-0.1.0
    container_name: rabbitmq
    volumes:
      - rabbitmq_etc:/etc/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq/
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE:-123456789}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - 4369
      - 5672:5672
      - 25672:25672
      - 15672:15672
volumes:
  pgdata:
  rails_cache:
  bundle:
  node_modules:
  enroll_bundle:
  enroll_node_modules:
  packs:
  rabbitmq_etc:
  rabbitmq_data:
  rabbitmq_logs:
  mongodb:
  mongodb_config:
